version: "3.8"
services:
  client:
    build:
      context: ./my-app
    ports:
      - "3000:80"  # React build serve trên Nginx port 80
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/MyTest
      - JWT_SECRET=mykey123
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
